name: Download, Extract and Run SSHX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-sshx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download SSHX tar.gz
        run: |
          wget https://sshx.s3.amazonaws.com/sshx-x86_64-unknown-linux-musl.tar.gz

      - name: Extract SSHX tar.gz
        run: |
          tar -xvzf sshx-x86_64-unknown-linux-musl.tar.gz

      - name: Run SSHX
        run: |
          chmod +x sshx
          ./sshx
