name: Python Script

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mine:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    # Matrix strategy to run 5 workers in parallel
    strategy:
      matrix:
        worker: [1, 2, 3, 4, 5]  # 5 workers in parallel

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository content

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # You can specify another Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rich

    - name: Run mining script with worker {{ matrix.worker }}
      run: |
        python num.py --worker {{ matrix.worker }}  # Pass worker number to num.py
